
# The name values.yaml comes from Helm.
# The Helm chart contains the actual templates for creating the Deployments, Services, ConfigMaps, Prometheus resources, Grafana resources, etc. 
# The values.yaml file supplies the configuration values that those templates use. The official kube-prometheus-stack chart explicitly describes its values.yaml as values passed into templates
# I'm configuring a pre-built application rather than manually defining every Kubernetes object like Deployment, Service, ConfigMap etc.


# To get the service name of a Helm chart application (such as prometheus and grafana) especially when using values.yml, by default, the service name for grafana created by the kube-prometheus-stack Helm chart follows the pattern [RELEASE-NAME]-grafana.
# In my setup, I used an argoCD application named "argo-monitoring" to release/deploy kube-prometheus-stack via helm. So "argo-monitoring" forms the RELEASE-NAME.
# Therefore the Grafana service is created as 'argo-monitoring-grafana.

# You can use this code to get the services names in a particular namespace: kubectl get svc -n <namespace>

# This is different from my app, because I explicitly created a service manifest and named it. So the argoCD application cant overwrite that.

grafana:

  # Sets Grafana admin login password
  adminPassword: "ThisIsATestPassword654@"      

  # username: "admin"
  service:

    # The Service is reachable internally within the Kubernetes cluster. 
    # This is actually perfect for my architecture because my ALB/Gateway can sit in front of it. Other types are: NodePort (Exposes a port on every Kubernetes node) and LoadBalancer (Requests an external load balancer)
    type: ClusterIP

    # the port exposed by the Service                                      
    port: 80          

    # the port Grafana container listens on                                   
    targetPort: 3000       

    # I encountered an issue where the alb used '/' as the health check path for my grafana service. 
    # The ALB health check path defaults to '/' because that’s the standard behavior of the AWS Load Balancer Controller when creating a target group from a Kubernetes Service. 
    # It doesn’t automatically know which path is appropriate for the application. It just uses the root by convention.

    # Many settings can be configured when installing the AWS Load Balancer Controller, but health check path is not one of them at the controller level. 
    # The reason is that the health check path is application‑specific. Different apps may use /, /health, /api/health, etc. The controller can't assume a default that works for all services.

    # Grafana’s root (/) does not return 200 OK; it returns a 302 redirect to /login (because you’re not authenticated). The ALB health check sees a 3xx code, considers the target unhealthy, and stops routing traffic.
    # Grafana has a dedicated health endpoint at "/api/health" that returns 200 OK without authentication, but the ALB won’t use it unless you explicitly tell it to either; 
    # Automatically using this values.yml manifest as shown below OR Manually using the CLI: kubectl annotate svc <service_name> -n default alb.ingress.kubernetes.io/healthcheck-path=/api/health 
    annotations:
      alb.ingress.kubernetes.io/healthcheck-path: /api/health

  nodeSelector:

    # Schedule only on monitoring nodes
    role: general_and_monitoring                              
  grafana.ini:
    server:

      # This is Grafana's public URL. It is the standard Grafana pattern when Grafana is served under a sub-path. Grafana needs to know that users reach it at /grafana, rather than at /. 
      # The %(... )s parts are Grafana variables that Grafana substitutes at runtime. So conceptually: http://builtbyedunoh.com:80/grafana
      root_url: "%(protocol)s://%(domain)s:%(http_port)s/grafana"     

      # serve_from_sub_path: true tells Grafana to actually serve its application from /grafana. It is required for /grafana path because I'm putting Grafana behind my domain: http://builtbyedunoh.com/grafana
      serve_from_sub_path: true

    auth:
      disable_login_form: true

    auth.jwt:
      enabled: true

      header_name: X-Amzn-Oidc-Data

      # These claims exist in the Cognito data token
      username_claim: cognito:username
      email_claim: email

      auto_sign_up: true

      role_attribute_path: ""
      
      role_attribute_strict: false

      jwk_set_url: "https://cognito-idp.eu-north-1.amazonaws.com/eu-north-1_h4EY7xK0b/.well-known/jwks.json"

      expected_issuer: "https://cognito-idp.eu-north-1.amazonaws.com/eu-north-1_h4EY7xK0b"


prometheus:
  service:
    type: ClusterIP

    # The port exposed by the Service
    port: 9090     

    # The port Prometheus container listens on                                     
    targetPort: 9090 
                                       
  prometheusSpec:                           
    replicas: 1
    nodeSelector:
      
      # Schedule only on monitoring nodes
      role: general_and_monitoring         

    # Keep metrics data for 15 days                    
    retention: 15d                                      
    storageSpec:

      # ephemeral, no Persistent Volume Claim (PVC) used for now. You can add EBS in production or even use s3                 
      emptyDir: {}                                      
          