
# ArgoCD need this yaml file to deploy resources/services. 

# Application 1: App
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-eks-app            # Name of the Application; must be unique within Argo CD.
  namespace: argocd             # Namespace where Argo CD is installed; this is where the Application resource lives.
spec:
  project: default              # The Argo CD project this Application belongs to. 'default' is the built-in project.
  source:                       # The source of the desired state. Here we use a single source.
    repoURL: https://github.com/eedunoh/Three-Tier-Web-Application-on-Amazon-EKS.git          # Git repository URL containing the application manifests.
    targetRevision: main        # The branch, tag, or commit to track.
    path: manifests             # Directory within the repository that contains the manifests (e.g deployment.yaml).
  destination:                  # Where to deploy the application
    server: https://kubernetes.default.svc                        # Kubernetes API server address. For in-cluster Argo CD, use the default service address.
    namespace: default          # Target namespace in the cluster where resources will be created.
  syncPolicy:                   # How Argo CD should keep the application in sync.
    automated:                  # Enable automatic synchronization when Git changes.
      prune: true               # Remove resources that exist in the cluster but no longer exist in Git.
      selfHeal: true            # Automatically revert manual changes to match the Git source of truth.


---


# Application 2: Monitoring
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-monitoring
  namespace: argocd
spec:
  project: default
  sources:                              # Use multiple sources because we need a Helm chart and a values file from different repositories.
    - repoURL: https://prometheus-community.github.io/helm-charts     # Source 1: The Helm chart from the Prometheus community repository.
      chart: kube-prometheus-stack      # Name of the Helm chart.
      targetRevision: 58.0.0            # Pin the chart version to ensure reproducibility.
      helm:                             # Helm-specific options.
        valueFiles:                     # This references a file from the second source (the one with ref: values). It basically says: "From the Git repository that I gave the alias values, go to monitoring/kube_prometheus_values.yaml."
          - $values/monitoring/kube_prometheus_values.yml
    - repoURL: https://github.com/eedunoh/Three-Tier-Web-Application-on-Amazon-EKS.git            # Source 2: Our Git repository containing the custom Helm values file.
      targetRevision: main              # Branch or tag to track in this Git repo.
      ref: values                       # An arbitrary name (ref) assigned to this source. It is used in the first source's $values path.
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

      # I encountered an issue where the Prometheus and Alertmanager monitoring tools were missing because their Custom Resource Definitions (CRDs) are too large for ArgoCD's default installation method. 
      # When ArgoCD installs applications, it tries to create a hidden backup copy of the entire CRD schema inside a tiny text slot in Kubernetes. 
      # However, the Prometheus CRD files are massive, and trying to force them into this tiny slot instantly triggers a Kubernetes safety limit that blocks anything larger than 262,144 bytes. 
      # Because of this block, the installation gets stuck halfway, leaving the monitoring "brain" unable to start up or create the rest of the tools.

      # The recommended solution is to add specific configuration options to the ArgoCD application settings to safely bypass this limit and handle the deployment cleanly:
      # 1. CreateNamespace=true: This tells ArgoCD to automatically create the destination namespace in the Kubernetes cluster if it doesn't already exist before trying to deploy any resources into it.
      
      # 2. SkipDryRunOnMissingResource=true: Before deploying, ArgoCD normally runs a "dry-run" pre-check against Kubernetes to ensure all resource types are recognized. This option tells ArgoCD to skip that pre-check for custom resources (like Prometheus or Alertmanager CRDs), preventing the installation from immediately failing if their definitions aren't fully registered in the cluster yet.
      
      # 3. ServerSideApply=true: This shifts the deployment tracking responsibility from the local ArgoCD client directly to the Kubernetes API server control plane. 
      # It completely stops ArgoCD from writing massive CRD tracking data into a tiny metadata text slot (kubectl.kubernetes.io/last-applied-configuration), effortlessly bypassing the strict 262,144-byte size limit that was previously breaking my deployment.
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
      - ServerSideApply=true


