
# The name values.yaml comes from Helm.
# The Helm chart contains the actual templates for creating the Deployments, Services, ConfigMaps, Prometheus resources, Grafana resources, etc. 
# The values.yaml file supplies the configuration values that those templates use. The official kube-prometheus-stack chart explicitly describes its values.yaml as values passed into templates
# I'm configuring a pre-built application rather than manually defining every Kubernetes object like Deployment, Service, ConfigMap etc.


# To get the service name of a Helm chart application (such as prometheus and grafana) especially when using values.yml, by default, the service name for grafana created by the kube-prometheus-stack Helm chart follows the pattern [RELEASE-NAME]-grafana.
# In my setup, I used an argoCD application named "argo-monitoring" to release/deploy kube-prometheus-stack via helm. So "argo-monitoring" forms the RELEASE-NAME.
# Therefore the Grafana service is created as 'argo-monitoring-grafana.

# You can use this code to get the services names in a particular namespace: kubectl get svc -n <namespace>

# This is different from my app, because I explicitly created a service manifest and named it. So the argoCD application cant overwrite that.

grafana:

  # Sets Grafana admin login password
  # adminPassword: "${GRAFANA_PASSWORD}"      
  # username: "admin"
  
  service:

    # The Service is reachable internally within the Kubernetes cluster. 
    # This is actually perfect for my architecture because my ALB/Gateway can sit in front of it. Other types are: NodePort (Exposes a port on every Kubernetes node) and LoadBalancer (Requests an external load balancer)
    type: ClusterIP

    # the port exposed by the Service                                      
    port: 80          

    # the port Grafana container listens on                                   
    targetPort: 3000       

    # I encountered an issue where the alb used '/' as the health check path for my grafana service. 
    # The ALB health check path defaults to '/' because that’s the standard behavior of the AWS Load Balancer Controller when creating a target group from a Kubernetes Service. 
    # It doesn’t automatically know which path is appropriate for the application. It just uses the root by convention.

    # Many settings can be configured when installing the AWS Load Balancer Controller, but health check path is not one of them at the controller level. 
    # The reason is that the health check path is application‑specific. Different apps may use /, /health, /api/health, etc. The controller can't assume a default that works for all services.

    # Grafana’s root (/) does not return 200 OK; it returns a 302 redirect to /login (because you’re not authenticated). The ALB health check sees a 3xx code, considers the target unhealthy, and stops routing traffic.
    # Grafana has a dedicated health endpoint at "/api/health" that returns 200 OK without authentication, but the ALB won’t use it unless you explicitly tell it to either; 
    # Automatically using this values.yml manifest as shown below OR Manually using the CLI: kubectl annotate svc <service_name> -n default alb.ingress.kubernetes.io/healthcheck-path=/api/health 
    annotations:
      alb.ingress.kubernetes.io/healthcheck-path: /api/health

  nodeSelector:

    # Schedule only on monitoring nodes
    role: general_and_monitoring                              
  grafana.ini:
    server:
      root_url: "https://www.builtbyedunoh.com/grafana"

      # serve_from_sub_path: true tells Grafana to actually serve its application from /grafana. It is required for /grafana path because I'm putting Grafana behind my domain: http://builtbyedunoh.com/grafana
      serve_from_sub_path: true

    auth:
      # Set to "true" if you want to use single sign-on. Else imput "false"
      disable_login_form: true

      # It only adds a redirect. Instead of rendering the empty HTML page, Grafana sends an HTTP 302 Redirect to Cognito. The login flow then proceeds normally.
      auto_login: true


    # Authenticate Grafana user using AWS Cognito
    # https://archive.grafana.com/docs/grafana/v12.3/setup-grafana/configure-access/configure-authentication/generic-oauth/#configure-team-synchronization#2
    auth.generic_oauth:

      # Enables the Generic OAuth authentication module in Grafana
      enabled: true

      # Display name for the login button (shown on Grafana's login page)
      name: Cognito

      # Cognito App Client ID (used to identify Grafana to Cognito)
      client_id: ${USER_POOL_CLIENT_ID}

      # Cognito App Client Secret (used to authenticate Grafana's token exchange requests)
      client_secret: ${USER_POOL_CLIENT_SECRET}

      # OAuth scopes requested; 'openid' is required for the ID token, 'email' and 'profile' provide user attributes
      scopes: openid email profile

      # Cognito endpoint for the Authorization Code Flow (redirects users to the login page)
      auth_url: https://${USER_POOL_DOMAIN}.auth.eu-north-1.amazoncognito.com/oauth2/authorize

      # Cognito endpoint Grafana calls internally to exchange the 'code' for access/ID tokens
      token_url: https://${USER_POOL_DOMAIN}.auth.eu-north-1.amazoncognito.com/oauth2/token

      # Cognito endpoint Grafana calls to get user profile details (email, name) using the access token
      api_url: https://${USER_POOL_DOMAIN}.auth.eu-north-1.amazoncognito.com/oauth2/userInfo

      # Allow new users from Cognito to auto-create accounts in Grafana on first login (vs. manual creation)
      allow_sign_up: true

      # Specifies which JSON field in the token/userInfo contains the user's email
      email_attribute_name: email

      # Tells Grafana which attribute to use as the user's login/username (Grafana will use the email to match accounts)
      login_attribute_path: email

      # Tells Grafana which attribute to use for the user's display name in the UI
      name_attribute_path: username


      # Cognito includes group membership as the cognito:groups claim in the ID and access tokens. Grafana’s Generic OAuth integration supports group‑based restrictions with two configuration options:
      # 1. groups_attribute_path: Tells Grafana where to find the groups in the OAuth response
      # 2. allowed_groups: List of groups whose members are allowed to log in

      # I want ONLY users in the admin group to access the app:
      # Tell Grafana the groups are in the "cognito:groups" claim
      groups_attribute_path: "cognito:groups"
      
      # Only allow users in the "admin" group (replace with your group name)
      allowed_groups: "admin"
      
      # Optional: prevent login if role mapping fails
      role_attribute_strict: true

      # Tells Grafana to immediately redirect to Cognito
      auto_login: true



prometheus:
  service:
    type: ClusterIP

    # The port exposed by the Service
    port: 9090     

    # The port Prometheus container listens on                                     
    targetPort: 9090 
                                       
  prometheusSpec:                           
    replicas: 1
    nodeSelector:
      
      # Schedule only on monitoring nodes
      role: general_and_monitoring         

    # Keep metrics data for 15 days                    
    retention: 15d                                      
    storageSpec:

      # ephemeral, no Persistent Volume Claim (PVC) used for now. You can add EBS in production or even use s3                 
      emptyDir: {}                                      